# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'plover_cat/plover_cat.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PloverCAT(object):
    def setupUi(self, PloverCAT):
        PloverCAT.setObjectName("PloverCAT")
        PloverCAT.resize(544, 272)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(PloverCAT.sizePolicy().hasHeightForWidth())
        PloverCAT.setSizePolicy(sizePolicy)
        PloverCAT.setMinimumSize(QtCore.QSize(32, 0))
        self.centralwidget = QtWidgets.QWidget(PloverCAT)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.strokeList = QtWidgets.QListWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.strokeList.sizePolicy().hasHeightForWidth())
        self.strokeList.setSizePolicy(sizePolicy)
        self.strokeList.setObjectName("strokeList")
        self.horizontalLayout.addWidget(self.strokeList)
        self.textEdit = PloverCATEditor(self.centralwidget)
        self.textEdit.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit.sizePolicy().hasHeightForWidth())
        self.textEdit.setSizePolicy(sizePolicy)
        self.textEdit.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.textEdit.setObjectName("textEdit")
        self.horizontalLayout.addWidget(self.textEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.retranslateButton = QtWidgets.QPushButton(self.centralwidget)
        self.retranslateButton.setObjectName("retranslateButton")
        self.verticalLayout.addWidget(self.retranslateButton)
        PloverCAT.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(PloverCAT)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 544, 24))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        PloverCAT.setMenuBar(self.menubar)
        self.actionOpen_Stroke_Log = QtWidgets.QAction(PloverCAT)
        self.actionOpen_Stroke_Log.setObjectName("actionOpen_Stroke_Log")
        self.actionOpen_Project = QtWidgets.QAction(PloverCAT)
        self.actionOpen_Project.setObjectName("actionOpen_Project")
        self.actionOpen = QtWidgets.QAction(PloverCAT)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave_As = QtWidgets.QAction(PloverCAT)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionImport_Paper = QtWidgets.QAction(PloverCAT)
        self.actionImport_Paper.setObjectName("actionImport_Paper")
        self.actionImport_Raw = QtWidgets.QAction(PloverCAT)
        self.actionImport_Raw.setObjectName("actionImport_Raw")
        self.actionRemove_Edit = QtWidgets.QAction(PloverCAT)
        self.actionRemove_Edit.setObjectName("actionRemove_Edit")
        self.actionExport = QtWidgets.QAction(PloverCAT)
        self.actionExport.setObjectName("actionExport")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addAction(self.actionImport_Paper)
        self.menuFile.addAction(self.actionImport_Raw)
        self.menuFile.addAction(self.actionExport)
        self.menuEdit.addAction(self.actionRemove_Edit)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())

        self.retranslateUi(PloverCAT)
        QtCore.QMetaObject.connectSlotsByName(PloverCAT)

    def retranslateUi(self, PloverCAT):
        _translate = QtCore.QCoreApplication.translate
        PloverCAT.setWindowTitle(_translate("PloverCAT", "MainWindow"))
        self.retranslateButton.setText(_translate("PloverCAT", "Retranslate"))
        self.menuFile.setTitle(_translate("PloverCAT", "File"))
        self.menuEdit.setTitle(_translate("PloverCAT", "Edit"))
        self.actionOpen_Stroke_Log.setText(_translate("PloverCAT", "Open Stroke Log..."))
        self.actionOpen_Project.setText(_translate("PloverCAT", "Open Project..."))
        self.actionOpen.setText(_translate("PloverCAT", "Open..."))
        self.actionSave_As.setText(_translate("PloverCAT", "Save As..."))
        self.actionImport_Paper.setText(_translate("PloverCAT", "Import Paper Tape Log"))
        self.actionImport_Raw.setText(_translate("PloverCAT", "Import Raw Log..."))
        self.actionRemove_Edit.setText(_translate("PloverCAT", "Remove Edit"))
        self.actionExport.setText(_translate("PloverCAT", "Export as Text..."))

from plover_cat.TextEditor import PloverCATEditor
from . import resources_rc
